### ISSUE TITLE
eightcells test fails

### ISSUE THREAD

**Issue by eivindjahren** [equinor/res2df#482]
FAILED tests/test_summary_restarts.py::test_summary_restarts[more-than-132-chars-due-to-abspath] - TypeError: run_reservoir_simulator() missing 1 required positional argument: 'datafile'

introduced in https://github.com/equinor/res2df/commit/e91c360b2c21a36a95a92278e161ab6c29c20ac7
